//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://cleancode.ru/snow/memoryDumpSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://cleancode.ru/snow/memoryDumpSchema", IsNullable = false)]
public partial class MemoryDump
{

    private string cellsOffsetField;

    private DumpMemoryCell[] cellsField;

    /// <remarks/>
    public string CellsOffset
    {
        get { return this.cellsOffsetField; }
        set { this.cellsOffsetField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Cell", IsNullable = false)]
    public DumpMemoryCell[] Cells
    {
        get { return this.cellsField; }
        set { this.cellsField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cleancode.ru/snow/memoryDumpSchema")]
public partial class DumpMemoryCell
{

    private string addressField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Address
    {
        get { return this.addressField; }
        set { this.addressField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get { return this.valueField; }
        set { this.valueField = value; }
    }

    public DumpMemoryCell(string address, string value)
    {
        this.addressField = address;
        this.valueField = value;
    }

    public DumpMemoryCell() { }
}
